package br.edu.uag.aruagi.model;
// Generated 09/08/2014 12:29:58 by Hibernate Tools 3.6.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AplicacaoFrase generated by hbm2java
 */
@Entity
@Table(name = "aplicacao_frase", schema = "public"
)
public class AplicacaoFrase implements java.io.Serializable {

    private AplicacaoFraseId id;
    private FraseLatim fraseLatim;
    private PalavraLatim palavraLatim;
    private Integer usuario;
    private Boolean status;

    public AplicacaoFrase() {
    }

    public AplicacaoFrase(AplicacaoFraseId id, FraseLatim fraseLatim, PalavraLatim palavraLatim) {
        this.id = id;
        this.fraseLatim = fraseLatim;
        this.palavraLatim = palavraLatim;
    }

    public AplicacaoFrase(AplicacaoFraseId id, FraseLatim fraseLatim, PalavraLatim palavraLatim, Integer usuario, Boolean status) {
        this.id = id;
        this.fraseLatim = fraseLatim;
        this.palavraLatim = palavraLatim;
        this.usuario = usuario;
        this.status = status;
    }

    @EmbeddedId
    @AttributeOverrides({
        @AttributeOverride(name = "palavraLatim", column = @Column(name = "palavra_latim", nullable = false)),
        @AttributeOverride(name = "fraseLatim", column = @Column(name = "frase_latim", nullable = false))})
    public AplicacaoFraseId getId() {
        return this.id;
    }

    public void setId(AplicacaoFraseId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "frase_latim", nullable = false, insertable = false, updatable = false)
    public FraseLatim getFraseLatim() {
        return this.fraseLatim;
    }

    public void setFraseLatim(FraseLatim fraseLatim) {
        this.fraseLatim = fraseLatim;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "palavra_latim", nullable = false, insertable = false, updatable = false)
    public PalavraLatim getPalavraLatim() {
        return this.palavraLatim;
    }

    public void setPalavraLatim(PalavraLatim palavraLatim) {
        this.palavraLatim = palavraLatim;
    }

    @Column(name = "usuario")
    public Integer getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Integer usuario) {
        this.usuario = usuario;
    }

    @Column(name = "status")
    public Boolean getStatus() {
        return this.status;
    }

    public void setStatus(Boolean status) {
        this.status = status;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 37 * hash + (this.id != null ? this.id.hashCode() : 0);
        hash = 37 * hash + (this.fraseLatim != null ? this.fraseLatim.hashCode() : 0);
        hash = 37 * hash + (this.palavraLatim != null ? this.palavraLatim.hashCode() : 0);
        hash = 37 * hash + (this.usuario != null ? this.usuario.hashCode() : 0);
        hash = 37 * hash + (this.status != null ? this.status.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final AplicacaoFrase other = (AplicacaoFrase) obj;
        if (this.id != other.id && (this.id == null || !this.id.equals(other.id))) {
            return false;
        }
        if (this.fraseLatim != other.fraseLatim && (this.fraseLatim == null || !this.fraseLatim.equals(other.fraseLatim))) {
            return false;
        }
        if (this.palavraLatim != other.palavraLatim && (this.palavraLatim == null || !this.palavraLatim.equals(other.palavraLatim))) {
            return false;
        }
        if (this.usuario != other.usuario && (this.usuario == null || !this.usuario.equals(other.usuario))) {
            return false;
        }
        if (this.status != other.status && (this.status == null || !this.status.equals(other.status))) {
            return false;
        }
        return true;
    }

}
