package br.edu.uag.aruagi.model;
// Generated 09/08/2014 12:29:58 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AplicacaoFraseId generated by hbm2java
 */
@Embeddable
public class AplicacaoFraseId implements java.io.Serializable {

    private int palavraLatim;
    private int fraseLatim;

    public AplicacaoFraseId() {
    }

    public AplicacaoFraseId(int palavraLatim, int fraseLatim) {
        this.palavraLatim = palavraLatim;
        this.fraseLatim = fraseLatim;
    }

    @Column(name = "palavra_latim", nullable = false)
    public int getPalavraLatim() {
        return this.palavraLatim;
    }

    public void setPalavraLatim(int palavraLatim) {
        this.palavraLatim = palavraLatim;
    }

    @Column(name = "frase_latim", nullable = false)
    public int getFraseLatim() {
        return this.fraseLatim;
    }

    public void setFraseLatim(int fraseLatim) {
        this.fraseLatim = fraseLatim;
    }

    @Override
    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof AplicacaoFraseId)) {
            return false;
        }
        AplicacaoFraseId castOther = (AplicacaoFraseId) other;

        return (this.getPalavraLatim() == castOther.getPalavraLatim())
                && (this.getFraseLatim() == castOther.getFraseLatim());
    }

    @Override
    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getPalavraLatim();
        result = 37 * result + this.getFraseLatim();
        return result;
    }

}
