package br.edu.uag.aruagi.model;
// Generated 09/08/2014 12:29:58 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CasoAplicadoId generated by hbm2java
 */
@Embeddable
public class CasoAplicadoId implements java.io.Serializable {

    private int palavraLatim;
    private int caso;

    public CasoAplicadoId() {
    }

    public CasoAplicadoId(int palavraLatim, int caso) {
        this.palavraLatim = palavraLatim;
        this.caso = caso;
    }

    @Column(name = "palavra_latim", nullable = false)
    public int getPalavraLatim() {
        return this.palavraLatim;
    }

    public void setPalavraLatim(int palavraLatim) {
        this.palavraLatim = palavraLatim;
    }

    @Column(name = "caso", nullable = false)
    public int getCaso() {
        return this.caso;
    }

    public void setCaso(int caso) {
        this.caso = caso;
    }

    @Override
    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof CasoAplicadoId)) {
            return false;
        }
        CasoAplicadoId castOther = (CasoAplicadoId) other;

        return (this.getPalavraLatim() == castOther.getPalavraLatim())
                && (this.getCaso() == castOther.getCaso());
    }

    @Override
    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getPalavraLatim();
        result = 37 * result + this.getCaso();
        return result;
    }

}
