package br.edu.uag.aruagi.model;
// Generated 09/08/2014 12:29:58 by Hibernate Tools 3.6.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CasoAplicado generated by hbm2java
 */
@Entity
@Table(name = "caso_aplicado", schema = "public"
)
public class CasoAplicado implements java.io.Serializable {
    
    private CasoAplicadoId id;
    private PalavraLatim palavraLatim;
    private Caso caso;
    private Integer usuario;
    private Boolean status;
    
    public CasoAplicado() {
    }
    
    public CasoAplicado(CasoAplicadoId id, PalavraLatim palavraLatim, Caso caso) {
        this.id = id;
        this.palavraLatim = palavraLatim;
        this.caso = caso;
    }
    
    public CasoAplicado(CasoAplicadoId id, PalavraLatim palavraLatim, Caso caso, Integer usuario, Boolean status) {
        this.id = id;
        this.palavraLatim = palavraLatim;
        this.caso = caso;
        this.usuario = usuario;
        this.status = status;
    }
    
    @EmbeddedId
    @AttributeOverrides({
        @AttributeOverride(name = "palavraLatim", column = @Column(name = "palavra_latim", nullable = false)),
        @AttributeOverride(name = "caso", column = @Column(name = "caso", nullable = false))})
    public CasoAplicadoId getId() {
        return this.id;
    }
    
    public void setId(CasoAplicadoId id) {
        this.id = id;
    }
    
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "palavra_latim", nullable = false, insertable = false, updatable = false)
    public PalavraLatim getPalavraLatim() {
        return this.palavraLatim;
    }
    
    public void setPalavraLatim(PalavraLatim palavraLatim) {
        this.id.setPalavraLatim(palavraLatim.getId());
        this.palavraLatim = palavraLatim;
    }
    
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "caso", nullable = false, insertable = false, updatable = false)
    public Caso getCaso() {
        return this.caso;
    }
    
    public void setCaso(Caso caso) {
        this.id.setCaso(caso.getId());
        this.caso = caso;
    }
    
    @Column(name = "usuario")
    public Integer getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Integer usuario) {
        this.usuario = usuario;
    }
    
    @Column(name = "status")
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }
    
    @Override
    public int hashCode() {
        int hash = 3;
        hash = 67 * hash + (this.id != null ? this.id.hashCode() : 0);
        hash = 67 * hash + (this.palavraLatim != null ? this.palavraLatim.hashCode() : 0);
        hash = 67 * hash + (this.caso != null ? this.caso.hashCode() : 0);
        hash = 67 * hash + (this.usuario != null ? this.usuario.hashCode() : 0);
        hash = 67 * hash + (this.status != null ? this.status.hashCode() : 0);
        return hash;
    }
    
    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final CasoAplicado other = (CasoAplicado) obj;
        if (this.id != other.id && (this.id == null || !this.id.equals(other.id))) {
            return false;
        }
        if (this.palavraLatim != other.palavraLatim && (this.palavraLatim == null || !this.palavraLatim.equals(other.palavraLatim))) {
            return false;
        }
        if (this.caso != other.caso && (this.caso == null || !this.caso.equals(other.caso))) {
            return false;
        }
        if (this.usuario != other.usuario && (this.usuario == null || !this.usuario.equals(other.usuario))) {
            return false;
        }
        if (this.status != other.status && (this.status == null || !this.status.equals(other.status))) {
            return false;
        }
        return true;
    }
    
}
