package br.edu.uag.aruagi.model;
// Generated 09/08/2014 12:29:58 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DeclinacaoAplicadaId generated by hbm2java
 */
@Embeddable
public class DeclinacaoAplicadaId implements java.io.Serializable {

    private int declinacao;
    private int palavra;

    public DeclinacaoAplicadaId() {
    }

    public DeclinacaoAplicadaId(int declinacao, int palavra) {
        this.declinacao = declinacao;
        this.palavra = palavra;
    }

    @Column(name = "declinacao", nullable = false)
    public int getDeclinacao() {
        return this.declinacao;
    }

    public void setDeclinacao(int declinacao) {
        this.declinacao = declinacao;
    }

    @Column(name = "palavra", nullable = false)
    public int getPalavra() {
        return this.palavra;
    }

    public void setPalavra(int palavra) {
        this.palavra = palavra;
    }

    @Override
    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof DeclinacaoAplicadaId)) {
            return false;
        }
        DeclinacaoAplicadaId castOther = (DeclinacaoAplicadaId) other;

        return (this.getDeclinacao() == castOther.getDeclinacao())
                && (this.getPalavra() == castOther.getPalavra());
    }

    @Override
    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getDeclinacao();
        result = 37 * result + this.getPalavra();
        return result;
    }

}
