package br.edu.uag.aruagi.model;
// Generated 09/08/2014 12:29:58 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FrasePortugues generated by hbm2java
 */
@Entity
@Table(name = "frase_portugues", schema = "public"
)
public class FrasePortugues implements java.io.Serializable {

    private int id;
    private String frase;
    private Integer usuario;
    private Boolean status;
    private Set traduzFrases = new HashSet(0);

    public FrasePortugues() {
    }

    public FrasePortugues(int id, String frase) {
        this.id = id;
        this.frase = frase;
    }

    public FrasePortugues(int id, String frase, Integer usuario, Boolean status, Set traduzFrases) {
        this.id = id;
        this.frase = frase;
        this.usuario = usuario;
        this.status = status;
        this.traduzFrases = traduzFrases;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "frase", nullable = false)
    public String getFrase() {
        return this.frase;
    }

    public void setFrase(String frase) {
        this.frase = frase;
    }

    @Column(name = "usuario")
    public Integer getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Integer usuario) {
        this.usuario = usuario;
    }

    @Column(name = "status")
    public Boolean getStatus() {
        return this.status;
    }

    public void setStatus(Boolean status) {
        this.status = status;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "frasePortugues", targetEntity = TraduzFrase.class)
    public Set getTraduzFrases() {
        return this.traduzFrases;
    }

    public void setTraduzFrases(Set traduzFrases) {
        this.traduzFrases = traduzFrases;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 67 * hash + this.id;
        hash = 67 * hash + (this.frase != null ? this.frase.hashCode() : 0);
        hash = 67 * hash + (this.usuario != null ? this.usuario.hashCode() : 0);
        hash = 67 * hash + (this.status != null ? this.status.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final FrasePortugues other = (FrasePortugues) obj;
        if (this.id != other.id) {
            return false;
        }
        if ((this.frase == null) ? (other.frase != null) : !this.frase.equals(other.frase)) {
            return false;
        }
        if (this.usuario != other.usuario && (this.usuario == null || !this.usuario.equals(other.usuario))) {
            return false;
        }
        if (this.status != other.status && (this.status == null || !this.status.equals(other.status))) {
            return false;
        }
        return true;
    }

}
