package br.edu.uag.aruagi.model;
// Generated 09/08/2014 12:29:58 by Hibernate Tools 3.6.0

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * FrasePortugues generated by hbm2java
 */
@Entity
@Table(name = "frase_portugues", schema = "public"
)
public class FrasePortugues implements java.io.Serializable {

    private int id;
    private String frase;
    private Integer usuario;
    private Boolean status;
    private List<TraduzFrase> traduzFrases = new ArrayList<TraduzFrase>();
    private List<QuestaoTraduzFrase> questaoTraduzFrases = new ArrayList<QuestaoTraduzFrase>();

    public FrasePortugues() {
    }

    public FrasePortugues(int id, String frase) {
        this.id = id;
        this.frase = frase;
    }

    public FrasePortugues(int id, String frase, Integer usuario, Boolean status, List traduzFrases) {
        this.id = id;
        this.frase = frase;
        this.usuario = usuario;
        this.status = status;
        this.traduzFrases = traduzFrases;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "frase", nullable = false)
    public String getFrase() {
        return this.frase;
    }

    public void setFrase(String frase) {
        this.frase = frase;
    }

    @Column(name = "usuario")
    public Integer getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Integer usuario) {
        this.usuario = usuario;
    }

    @Column(name = "status")
    public Boolean getStatus() {
        return this.status;
    }

    public void setStatus(Boolean status) {
        this.status = status;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "frasePortugues", targetEntity = TraduzFrase.class)
    @Fetch(FetchMode.SUBSELECT)
    public List<TraduzFrase> getTraduzFrases() {
        return this.traduzFrases;
    }

    public void setTraduzFrases(List<TraduzFrase> traduzFrases) {
        this.traduzFrases = traduzFrases;
    }
    
    @OneToMany(fetch = FetchType.EAGER, mappedBy = "frasePortugues", targetEntity = QuestaoTraduzFrase.class)
    @Fetch(FetchMode.SUBSELECT)
    public List<QuestaoTraduzFrase> getQuestaoTraduzFrases() {
        return this.questaoTraduzFrases;
    }

    public void setQuestaoTraduzFrases(List<QuestaoTraduzFrase> questaoTraduzFrases) {
        this.questaoTraduzFrases = questaoTraduzFrases;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 83 * hash + this.id;
        hash = 83 * hash + (this.frase != null ? this.frase.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final FrasePortugues other = (FrasePortugues) obj;
        if (this.id != other.id) {
            return false;
        }
        if ((this.frase == null) ? (other.frase != null) : !this.frase.equals(other.frase)) {
            return false;
        }
        return true;
    }    

}
