package br.edu.uag.aruagi.model;
// Generated 09/08/2014 12:29:58 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FraseLatim generated by hbm2java
 */
@Entity
@Table(name = "frase_latim", schema = "public"
)
public class FraseLatim implements java.io.Serializable {

    private int id;
    private String frase;
    private Integer usuario;
    private Boolean status;
    private Set questaoTraduzFrases = new HashSet(0);
    private Set aplicacaoFrases = new HashSet(0);
    private Set traduzFrases = new HashSet(0);
    private Set questaoLacunas = new HashSet(0);

    public FraseLatim() {
    }

    public FraseLatim(int id, String frase) {
        this.id = id;
        this.frase = frase;
    }

    public FraseLatim(int id, String frase, Integer usuario, Boolean status, Set questaoTraduzFrases, Set aplicacaoFrases, Set traduzFrases, Set questaoLacunas) {
        this.id = id;
        this.frase = frase;
        this.usuario = usuario;
        this.status = status;
        this.questaoTraduzFrases = questaoTraduzFrases;
        this.aplicacaoFrases = aplicacaoFrases;
        this.traduzFrases = traduzFrases;
        this.questaoLacunas = questaoLacunas;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "frase", nullable = false)
    public String getFrase() {
        return this.frase;
    }

    public void setFrase(String frase) {
        this.frase = frase;
    }

    @Column(name = "usuario")
    public Integer getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Integer usuario) {
        this.usuario = usuario;
    }

    @Column(name = "status")
    public Boolean getStatus() {
        return this.status;
    }

    public void setStatus(Boolean status) {
        this.status = status;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "fraseLatim", targetEntity = QuestaoTraduzFrase.class)
    public Set getQuestaoTraduzFrases() {
        return this.questaoTraduzFrases;
    }

    public void setQuestaoTraduzFrases(Set questaoTraduzFrases) {
        this.questaoTraduzFrases = questaoTraduzFrases;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "fraseLatim", targetEntity = AplicacaoFrase.class)
    public Set getAplicacaoFrases() {
        return this.aplicacaoFrases;
    }

    public void setAplicacaoFrases(Set aplicacaoFrases) {
        this.aplicacaoFrases = aplicacaoFrases;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "fraseLatim", targetEntity = TraduzFrase.class)
    public Set getTraduzFrases() {
        return this.traduzFrases;
    }

    public void setTraduzFrases(Set traduzFrases) {
        this.traduzFrases = traduzFrases;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "fraseLatim", targetEntity = QuestaoLacuna.class)
    public Set getQuestaoLacunas() {
        return this.questaoLacunas;
    }

    public void setQuestaoLacunas(Set questaoLacunas) {
        this.questaoLacunas = questaoLacunas;
    }

}
