package br.edu.uag.aruagi.model;
// Generated 09/08/2014 12:29:58 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LinksQuestaoId generated by hbm2java
 */
@Embeddable
public class LinksQuestaoId implements java.io.Serializable {

    private int listaQuestoes;
    private int postagem;

    public LinksQuestaoId() {
    }

    public LinksQuestaoId(int listaQuestoes, int postagem) {
        this.listaQuestoes = listaQuestoes;
        this.postagem = postagem;
    }

    @Column(name = "lista_questoes", nullable = false)
    public int getListaQuestoes() {
        return this.listaQuestoes;
    }

    public void setListaQuestoes(int listaQuestoes) {
        this.listaQuestoes = listaQuestoes;
    }

    @Column(name = "postagem", nullable = false)
    public int getPostagem() {
        return this.postagem;
    }

    public void setPostagem(int postagem) {
        this.postagem = postagem;
    }

    @Override
    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof LinksQuestaoId)) {
            return false;
        }
        LinksQuestaoId castOther = (LinksQuestaoId) other;

        return (this.getListaQuestoes() == castOther.getListaQuestoes())
                && (this.getPostagem() == castOther.getPostagem());
    }

    @Override
    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getListaQuestoes();
        result = 37 * result + this.getPostagem();
        return result;
    }

}
