package br.edu.uag.aruagi.model;
// Generated 09/08/2014 12:29:58 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NivelAcesso generated by hbm2java
 */
@Entity
@Table(name = "nivel_acesso", schema = "public"
)
public class NivelAcesso implements java.io.Serializable {

    private int id;
    private String linkAcesso;
    private String descricao;
    private Boolean status;

    public NivelAcesso() {
    }

    public NivelAcesso(int id) {
        this.id = id;
    }

    public NivelAcesso(int id, String linkAcesso, String descricao) {
        this.id = id;
        this.linkAcesso = linkAcesso;
        this.descricao = descricao;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "link_acesso")
    public String getLinkAcesso() {
        return this.linkAcesso;
    }

    public void setLinkAcesso(String linkAcesso) {
        this.linkAcesso = linkAcesso;
    }

    @Column(name = "descricao")
    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    @Column(name = "status")
    public Boolean getStatus() {
        return status;
    }

    public void setStatus(Boolean status) {
        this.status = status;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 89 * hash + this.id;
        hash = 89 * hash + (this.linkAcesso != null ? this.linkAcesso.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
       return true;
    }

    

    @Override
    public String toString() {
        return ""+this.id;
    }

}
