package br.edu.uag.aruagi.model;
// Generated 09/08/2014 12:29:58 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * NivelAcesso generated by hbm2java
 */
@Entity
@Table(name = "nivel_acesso", schema = "public"
)
public class NivelAcesso implements java.io.Serializable {

    private int id;
    private String linkAcesso;
    private String descricao;
    private Set usuariosForIncluidoPor = new HashSet(0);

    public NivelAcesso() {
    }

    public NivelAcesso(int id) {
        this.id = id;
    }

    public NivelAcesso(int id, String linkAcesso, String descricao, Set usuariosForIncluidoPor) {
        this.id = id;
        this.linkAcesso = linkAcesso;
        this.descricao = descricao;
        this.usuariosForIncluidoPor = usuariosForIncluidoPor;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "link_acesso")
    public String getLinkAcesso() {
        return this.linkAcesso;
    }

    public void setLinkAcesso(String linkAcesso) {
        this.linkAcesso = linkAcesso;
    }

    @Column(name = "descricao")
    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "usuario", targetEntity = Usuario.class)
    public Set getUsuariosForIncluidoPor() {
        return this.usuariosForIncluidoPor;
    }

    public void setUsuariosForIncluidoPor(Set usuariosForIncluidoPor) {
        this.usuariosForIncluidoPor = usuariosForIncluidoPor;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 17 * hash + this.id;
        hash = 17 * hash + (this.linkAcesso != null ? this.linkAcesso.hashCode() : 0);
        hash = 17 * hash + (this.descricao != null ? this.descricao.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final NivelAcesso other = (NivelAcesso) obj;
        if (this.id != other.id) {
            return false;
        }
        if ((this.linkAcesso == null) ? (other.linkAcesso != null) : !this.linkAcesso.equals(other.linkAcesso)) {
            return false;
        }
        if ((this.descricao == null) ? (other.descricao != null) : !this.descricao.equals(other.descricao)) {
            return false;
        }
        return true;
    }

}
