package br.edu.uag.aruagi.model;
// Generated 09/08/2014 12:29:58 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * NivelQuestao generated by hbm2java
 */
@Entity
@Table(name = "nivel_questao", schema = "public"
)
public class NivelQuestao implements java.io.Serializable {

    private int id;
    private String descricao;
    private String observacoes;
    private Integer usuario;
    private Set questaoTraduzPalavras = new HashSet(0);
    private Set questaoGramaticals = new HashSet(0);
    private Set questaoTraduzFrases = new HashSet(0);
    private Set questaoLacunas = new HashSet(0);
    private Set questaoDeclinacaos = new HashSet(0);

    public NivelQuestao() {
    }

    public NivelQuestao(int id, String descricao) {
        this.id = id;
        this.descricao = descricao;
    }

    public NivelQuestao(int id, String descricao, String observacoes, Integer usuario, Set questaoTraduzPalavras, Set questaoGramaticals, Set questaoTraduzFrases, Set questaoLacunas, Set questaoDeclinacaos) {
        this.id = id;
        this.descricao = descricao;
        this.observacoes = observacoes;
        this.usuario = usuario;
        this.questaoTraduzPalavras = questaoTraduzPalavras;
        this.questaoGramaticals = questaoGramaticals;
        this.questaoTraduzFrases = questaoTraduzFrases;
        this.questaoLacunas = questaoLacunas;
        this.questaoDeclinacaos = questaoDeclinacaos;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "descricao", nullable = false)
    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    @Column(name = "observacoes")
    public String getObservacoes() {
        return this.observacoes;
    }

    public void setObservacoes(String observacoes) {
        this.observacoes = observacoes;
    }

    @Column(name = "usuario")
    public Integer getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Integer usuario) {
        this.usuario = usuario;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "nivelQuestao", targetEntity = QuestaoTraduzPalavra.class)
    public Set getQuestaoTraduzPalavras() {
        return this.questaoTraduzPalavras;
    }

    public void setQuestaoTraduzPalavras(Set questaoTraduzPalavras) {
        this.questaoTraduzPalavras = questaoTraduzPalavras;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "nivelQuestao", targetEntity = QuestaoGramatical.class)
    public Set getQuestaoGramaticals() {
        return this.questaoGramaticals;
    }

    public void setQuestaoGramaticals(Set questaoGramaticals) {
        this.questaoGramaticals = questaoGramaticals;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "nivelQuestao", targetEntity = QuestaoTraduzFrase.class)
    public Set getQuestaoTraduzFrases() {
        return this.questaoTraduzFrases;
    }

    public void setQuestaoTraduzFrases(Set questaoTraduzFrases) {
        this.questaoTraduzFrases = questaoTraduzFrases;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "nivelQuestao", targetEntity = QuestaoLacuna.class)
    public Set getQuestaoLacunas() {
        return this.questaoLacunas;
    }

    public void setQuestaoLacunas(Set questaoLacunas) {
        this.questaoLacunas = questaoLacunas;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "nivelQuestao", targetEntity = QuestaoDeclinacao.class)
    public Set getQuestaoDeclinacaos() {
        return this.questaoDeclinacaos;
    }

    public void setQuestaoDeclinacaos(Set questaoDeclinacaos) {
        this.questaoDeclinacaos = questaoDeclinacaos;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 97 * hash + this.id;
        hash = 97 * hash + (this.descricao != null ? this.descricao.hashCode() : 0);
        hash = 97 * hash + (this.observacoes != null ? this.observacoes.hashCode() : 0);
        hash = 97 * hash + (this.usuario != null ? this.usuario.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final NivelQuestao other = (NivelQuestao) obj;
        if (this.id != other.id) {
            return false;
        }
        if ((this.descricao == null) ? (other.descricao != null) : !this.descricao.equals(other.descricao)) {
            return false;
        }
        if ((this.observacoes == null) ? (other.observacoes != null) : !this.observacoes.equals(other.observacoes)) {
            return false;
        }
        if (this.usuario != other.usuario && (this.usuario == null || !this.usuario.equals(other.usuario))) {
            return false;
        }
        return true;
    }

}
