package br.edu.uag.aruagi.model;
// Generated 09/08/2014 12:29:58 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PalavrasClassificadasId generated by hbm2java
 */
@Embeddable
public class PalavrasClassificadasId implements java.io.Serializable {

    private int palavraLatim;
    private int classificacao;

    public PalavrasClassificadasId() {
    }

    public PalavrasClassificadasId(int palavraLatim, int classificacao) {
        this.palavraLatim = palavraLatim;
        this.classificacao = classificacao;
    }

    @Column(name = "palavra_latim", nullable = false)
    public int getPalavraLatim() {
        return this.palavraLatim;
    }

    public void setPalavraLatim(int palavraLatim) {
        this.palavraLatim = palavraLatim;
    }

    @Column(name = "classificacao", nullable = false)
    public int getClassificacao() {
        return this.classificacao;
    }

    public void setClassificacao(int classificacao) {
        this.classificacao = classificacao;
    }

    @Override
    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof PalavrasClassificadasId)) {
            return false;
        }
        PalavrasClassificadasId castOther = (PalavrasClassificadasId) other;

        return (this.getPalavraLatim() == castOther.getPalavraLatim())
                && (this.getClassificacao() == castOther.getClassificacao());
    }

    @Override
    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getPalavraLatim();
        result = 37 * result + this.getClassificacao();
        return result;
    }

}
