package br.edu.uag.aruagi.model;
// Generated 09/08/2014 12:29:58 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PalavrasDeclinadasId generated by hbm2java
 */
@Embeddable
public class PalavrasDeclinadasId implements java.io.Serializable {

    private int palavraLatim;
    private int palavraDeclinada;

    public PalavrasDeclinadasId() {
    }

    public PalavrasDeclinadasId(int palavraLatim, int palavraDeclinada, boolean status) {
        this.palavraLatim = palavraLatim;
        this.palavraDeclinada = palavraDeclinada;
    }

    @Column(name = "palavra_latim", nullable = false)
    public int getPalavraLatim() {
        return this.palavraLatim;
    }

    public void setPalavraLatim(int palavraLatim) {
        this.palavraLatim = palavraLatim;
    }

    @Column(name = "palavra_declinada", nullable = false)
    public int getPalavraDeclinada() {
        return this.palavraDeclinada;
    }

    public void setPalavraDeclinada(int palavraDeclinada) {
        this.palavraDeclinada = palavraDeclinada;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 71 * hash + this.palavraLatim;
        hash = 71 * hash + this.palavraDeclinada;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final PalavrasDeclinadasId other = (PalavrasDeclinadasId) obj;
        if (this.palavraLatim != other.palavraLatim) {
            return false;
        }
        if (this.palavraDeclinada != other.palavraDeclinada) {
            return false;
        }
        return true;
    }

}
