package br.edu.uag.aruagi.model;
// Generated 09/08/2014 12:29:58 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PalavrasDeclinadasId generated by hbm2java
 */
@Embeddable
public class PalavrasDeclinadasId implements java.io.Serializable {

    private int palavraLatim;
    private int palavraDeclinada;

    public PalavrasDeclinadasId() {
    }

    public PalavrasDeclinadasId(int palavraLatim, int palavraDeclinada) {
        this.palavraLatim = palavraLatim;
        this.palavraDeclinada = palavraDeclinada;
    }

    @Column(name = "palavra_latim", nullable = false)
    public int getPalavraLatim() {
        return this.palavraLatim;
    }

    public void setPalavraLatim(int palavraLatim) {
        this.palavraLatim = palavraLatim;
    }

    @Column(name = "palavra_declinada", nullable = false)
    public int getPalavraDeclinada() {
        return this.palavraDeclinada;
    }

    public void setPalavraDeclinada(int palavraDeclinada) {
        this.palavraDeclinada = palavraDeclinada;
    }

    @Override
    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof PalavrasDeclinadasId)) {
            return false;
        }
        PalavrasDeclinadasId castOther = (PalavrasDeclinadasId) other;

        return (this.getPalavraLatim() == castOther.getPalavraLatim())
                && (this.getPalavraDeclinada() == castOther.getPalavraDeclinada());
    }

    @Override
    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getPalavraLatim();
        result = 37 * result + this.getPalavraDeclinada();
        return result;
    }

}
