package br.edu.uag.aruagi.model;
// Generated 09/08/2014 12:29:58 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PalavraLatim generated by hbm2java
 */
@Entity
@Table(name = "palavra_latim", schema = "public"
)
public class PalavraLatim implements java.io.Serializable {

    private int id;
    private String palavra;
    private Integer usuario;
    private Boolean status;
    private Set casoAplicados = new HashSet(0);
    private Set aplicacaoFrases = new HashSet(0);
    private Set traduzPalavras = new HashSet(0);
    private Set palavrasDeclinadasesForPalavraLatim = new HashSet(0);
    private Set palavrasDeclinadasesForPalavraDeclinada = new HashSet(0);
    private Set palavrasClassificadases = new HashSet(0);
    private Set questaoGramaticals = new HashSet(0);
    private Set questaoDeclinacaos = new HashSet(0);
    private Set radicals = new HashSet(0);
    private Set declinacaoAplicadas = new HashSet(0);
    private Set questaoTraduzPalavras = new HashSet(0);

    public PalavraLatim() {
    }

    public PalavraLatim(int id, String palavra) {
        this.id = id;
        this.palavra = palavra;
    }

    public PalavraLatim(int id, String palavra, Integer usuario, Boolean status, Set casoAplicados, Set aplicacaoFrases, Set traduzPalavras, Set palavrasDeclinadasesForPalavraLatim, Set palavrasDeclinadasesForPalavraDeclinada, Set palavrasClassificadases, Set questaoGramaticals, Set questaoDeclinacaos, Set radicals, Set declinacaoAplicadas, Set questaoTraduzPalavras) {
        this.id = id;
        this.palavra = palavra;
        this.usuario = usuario;
        this.status = status;
        this.casoAplicados = casoAplicados;
        this.aplicacaoFrases = aplicacaoFrases;
        this.traduzPalavras = traduzPalavras;
        this.palavrasDeclinadasesForPalavraLatim = palavrasDeclinadasesForPalavraLatim;
        this.palavrasDeclinadasesForPalavraDeclinada = palavrasDeclinadasesForPalavraDeclinada;
        this.palavrasClassificadases = palavrasClassificadases;
        this.questaoGramaticals = questaoGramaticals;
        this.questaoDeclinacaos = questaoDeclinacaos;
        this.radicals = radicals;
        this.declinacaoAplicadas = declinacaoAplicadas;
        this.questaoTraduzPalavras = questaoTraduzPalavras;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "palavra", nullable = false)
    public String getPalavra() {
        return this.palavra;
    }

    public void setPalavra(String palavra) {
        this.palavra = palavra;
    }

    @Column(name = "usuario")
    public Integer getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Integer usuario) {
        this.usuario = usuario;
    }

    @Column(name = "status")
    public Boolean getStatus() {
        return this.status;
    }

    public void setStatus(Boolean status) {
        this.status = status;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "palavraLatim", targetEntity = CasoAplicado.class)
    public Set getCasoAplicados() {
        return this.casoAplicados;
    }

    public void setCasoAplicados(Set casoAplicados) {
        this.casoAplicados = casoAplicados;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "palavraLatim", targetEntity = AplicacaoFrase.class)
    public Set getAplicacaoFrases() {
        return this.aplicacaoFrases;
    }

    public void setAplicacaoFrases(Set aplicacaoFrases) {
        this.aplicacaoFrases = aplicacaoFrases;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "palavraLatim", targetEntity = TraduzPalavra.class)
    public Set getTraduzPalavras() {
        return this.traduzPalavras;
    }

    public void setTraduzPalavras(Set traduzPalavras) {
        this.traduzPalavras = traduzPalavras;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "palavraLatimByPalavraLatim", targetEntity = PalavrasDeclinadas.class)
    public Set getPalavrasDeclinadasesForPalavraLatim() {
        return this.palavrasDeclinadasesForPalavraLatim;
    }

    public void setPalavrasDeclinadasesForPalavraLatim(Set palavrasDeclinadasesForPalavraLatim) {
        this.palavrasDeclinadasesForPalavraLatim = palavrasDeclinadasesForPalavraLatim;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "palavraLatimByPalavraDeclinada", targetEntity = PalavrasDeclinadas.class)
    public Set getPalavrasDeclinadasesForPalavraDeclinada() {
        return this.palavrasDeclinadasesForPalavraDeclinada;
    }

    public void setPalavrasDeclinadasesForPalavraDeclinada(Set palavrasDeclinadasesForPalavraDeclinada) {
        this.palavrasDeclinadasesForPalavraDeclinada = palavrasDeclinadasesForPalavraDeclinada;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "palavraLatim", targetEntity = PalavrasClassificadas.class)
    public Set getPalavrasClassificadases() {
        return this.palavrasClassificadases;
    }

    public void setPalavrasClassificadases(Set palavrasClassificadases) {
        this.palavrasClassificadases = palavrasClassificadases;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "palavraLatim", targetEntity = QuestaoGramatical.class)
    public Set getQuestaoGramaticals() {
        return this.questaoGramaticals;
    }

    public void setQuestaoGramaticals(Set questaoGramaticals) {
        this.questaoGramaticals = questaoGramaticals;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "palavraLatim", targetEntity = QuestaoDeclinacao.class)
    public Set getQuestaoDeclinacaos() {
        return this.questaoDeclinacaos;
    }

    public void setQuestaoDeclinacaos(Set questaoDeclinacaos) {
        this.questaoDeclinacaos = questaoDeclinacaos;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "palavraLatim", targetEntity = Radical.class)
    public Set getRadicals() {
        return this.radicals;
    }

    public void setRadicals(Set radicals) {
        this.radicals = radicals;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "palavraLatim", targetEntity = DeclinacaoAplicada.class)
    public Set getDeclinacaoAplicadas() {
        return this.declinacaoAplicadas;
    }

    public void setDeclinacaoAplicadas(Set declinacaoAplicadas) {
        this.declinacaoAplicadas = declinacaoAplicadas;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "palavraLatim", targetEntity = QuestaoTraduzPalavra.class)
    public Set getQuestaoTraduzPalavras() {
        return this.questaoTraduzPalavras;
    }

    public void setQuestaoTraduzPalavras(Set questaoTraduzPalavras) {
        this.questaoTraduzPalavras = questaoTraduzPalavras;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 67 * hash + this.id;
        hash = 67 * hash + (this.palavra != null ? this.palavra.hashCode() : 0);
        hash = 67 * hash + (this.usuario != null ? this.usuario.hashCode() : 0);
        hash = 67 * hash + (this.status != null ? this.status.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final PalavraLatim other = (PalavraLatim) obj;
        if (this.id != other.id) {
            return false;
        }
        if ((this.palavra == null) ? (other.palavra != null) : !this.palavra.equals(other.palavra)) {
            return false;
        }
        if (this.usuario != other.usuario && (this.usuario == null || !this.usuario.equals(other.usuario))) {
            return false;
        }
        if (this.status != other.status && (this.status == null || !this.status.equals(other.status))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return String.valueOf(getId());
    }

}
