package br.edu.uag.aruagi.model;
// Generated 09/08/2014 12:29:58 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PessoaGramatical generated by hbm2java
 */
@Entity
@Table(name = "pessoa_gramatical", schema = "public"
)
public class PessoaGramatical implements java.io.Serializable {

    private int id;
    private String descricao;
    private String flexao;
    private Integer usuario;
    private Boolean status;
    private Set indicadorTempoVerbals = new HashSet(0);
    private Set indicadorPessoaGramaticals = new HashSet(0);
    private Set radicals = new HashSet(0);
    private Set questaoGramaticals = new HashSet(0);

    public PessoaGramatical() {
    }

    public PessoaGramatical(int id, String descricao, String flexao) {
        this.id = id;
        this.descricao = descricao;
        this.flexao = flexao;
    }

    public PessoaGramatical(int id, String descricao, String flexao, Integer usuario, Boolean status, Set indicadorTempoVerbals, Set indicadorPessoaGramaticals, Set radicals, Set questaoGramaticals) {
        this.id = id;
        this.descricao = descricao;
        this.flexao = flexao;
        this.usuario = usuario;
        this.status = status;
        this.indicadorTempoVerbals = indicadorTempoVerbals;
        this.indicadorPessoaGramaticals = indicadorPessoaGramaticals;
        this.radicals = radicals;
        this.questaoGramaticals = questaoGramaticals;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "descricao", nullable = false)
    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    @Column(name = "flexao", nullable = false)
    public String getFlexao() {
        return this.flexao;
    }

    public void setFlexao(String flexao) {
        this.flexao = flexao;
    }

    @Column(name = "usuario")
    public Integer getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Integer usuario) {
        this.usuario = usuario;
    }

    @Column(name = "status")
    public Boolean getStatus() {
        return this.status;
    }

    public void setStatus(Boolean status) {
        this.status = status;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "pessoaGramatical", targetEntity = IndicadorTempoVerbal.class)
    public Set getIndicadorTempoVerbals() {
        return this.indicadorTempoVerbals;
    }

    public void setIndicadorTempoVerbals(Set indicadorTempoVerbals) {
        this.indicadorTempoVerbals = indicadorTempoVerbals;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "pessoaGramatical", targetEntity = IndicadorPessoaGramatical.class)
    public Set getIndicadorPessoaGramaticals() {
        return this.indicadorPessoaGramaticals;
    }

    public void setIndicadorPessoaGramaticals(Set indicadorPessoaGramaticals) {
        this.indicadorPessoaGramaticals = indicadorPessoaGramaticals;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "pessoaGramatical", targetEntity = Radical.class)
    public Set getRadicals() {
        return this.radicals;
    }

    public void setRadicals(Set radicals) {
        this.radicals = radicals;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "pessoaGramatical", targetEntity = QuestaoGramatical.class)
    public Set getQuestaoGramaticals() {
        return this.questaoGramaticals;
    }

    public void setQuestaoGramaticals(Set questaoGramaticals) {
        this.questaoGramaticals = questaoGramaticals;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 17 * hash + this.id;
        hash = 17 * hash + (this.descricao != null ? this.descricao.hashCode() : 0);
        hash = 17 * hash + (this.flexao != null ? this.flexao.hashCode() : 0);
        hash = 17 * hash + (this.usuario != null ? this.usuario.hashCode() : 0);
        hash = 17 * hash + (this.status != null ? this.status.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final PessoaGramatical other = (PessoaGramatical) obj;
        if (this.id != other.id) {
            return false;
        }
        if ((this.descricao == null) ? (other.descricao != null) : !this.descricao.equals(other.descricao)) {
            return false;
        }
        if ((this.flexao == null) ? (other.flexao != null) : !this.flexao.equals(other.flexao)) {
            return false;
        }
        if (this.usuario != other.usuario && (this.usuario == null || !this.usuario.equals(other.usuario))) {
            return false;
        }
        if (this.status != other.status && (this.status == null || !this.status.equals(other.status))) {
            return false;
        }
        return true;
    }

}
