package br.edu.uag.aruagi.model;
// Generated 09/08/2014 12:29:58 by Hibernate Tools 3.6.0

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Postagem generated by hbm2java
 */
@Entity
@Table(name = "postagem", schema = "public"
)
public class Postagem implements java.io.Serializable {

    private int id;
    private String titulo;
    private String link;
    private Date data;
    private String conteudo;
    private Integer usuario;
    private Boolean status;
    private List<VideosPostagem> videosPostagems;
    private Set linksQuestaos = new HashSet(0);

    public Postagem() {
    }

    public Postagem(int id, Date data, String conteudo) {
        this.id = id;
        this.data = data;
        this.conteudo = conteudo;
    }

    public Postagem(int id, String titulo, String link, Date data, String conteudo, Integer usuario, Boolean status, List<VideosPostagem> videosPostagems, Set linksQuestaos) {
        this.id = id;
        this.titulo = titulo;
        this.link = link;
        this.data = data;
        this.conteudo = conteudo;
        this.usuario = usuario;
        this.status = status;
        this.videosPostagems = videosPostagems;
        this.linksQuestaos = linksQuestaos;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "titulo")
    public String getTitulo() {
        return this.titulo;
    }

    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    @Column(name = "link")
    public String getLink() {
        return this.link;
    }

    public void setLink(String link) {
        this.link = link;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "data", nullable = false, length = 13)
    public Date getData() {
        return this.data;
    }

    public void setData(Date data) {
        this.data = data;
    }

    @Column(name = "conteudo", nullable = false)
    public String getConteudo() {
        return this.conteudo;
    }

    public void setConteudo(String conteudo) {
        this.conteudo = conteudo;
    }

    @Column(name = "usuario")
    public Integer getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Integer usuario) {
        this.usuario = usuario;
    }

    @Column(name = "status")
    public Boolean getStatus() {
        return this.status;
    }

    public void setStatus(Boolean status) {
        this.status = status;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "postagem", targetEntity = VideosPostagem.class)
    public List<VideosPostagem> getVideosPostagems() {
        return this.videosPostagems;
    }

    public void setVideosPostagems(List<VideosPostagem> videosPostagems) {
        this.videosPostagems = videosPostagems;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "postagem", targetEntity = LinksQuestao.class)
    public Set getLinksQuestaos() {
        return this.linksQuestaos;
    }

    public void setLinksQuestaos(Set linksQuestaos) {
        this.linksQuestaos = linksQuestaos;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 73 * hash + this.id;
        hash = 73 * hash + (this.titulo != null ? this.titulo.hashCode() : 0);
        hash = 73 * hash + (this.link != null ? this.link.hashCode() : 0);
        hash = 73 * hash + (this.data != null ? this.data.hashCode() : 0);
        hash = 73 * hash + (this.conteudo != null ? this.conteudo.hashCode() : 0);
        hash = 73 * hash + (this.usuario != null ? this.usuario.hashCode() : 0);
        hash = 73 * hash + (this.status != null ? this.status.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Postagem other = (Postagem) obj;
        if (this.id != other.id) {
            return false;
        }
        if ((this.titulo == null) ? (other.titulo != null) : !this.titulo.equals(other.titulo)) {
            return false;
        }
        if ((this.link == null) ? (other.link != null) : !this.link.equals(other.link)) {
            return false;
        }
        if (this.data != other.data && (this.data == null || !this.data.equals(other.data))) {
            return false;
        }
        if ((this.conteudo == null) ? (other.conteudo != null) : !this.conteudo.equals(other.conteudo)) {
            return false;
        }
        if (this.usuario != other.usuario && (this.usuario == null || !this.usuario.equals(other.usuario))) {
            return false;
        }
        if (this.status != other.status && (this.status == null || !this.status.equals(other.status))) {
            return false;
        }
        return true;
    }

}
