package br.edu.uag.aruagi.model;
// Generated 09/08/2014 12:29:58 by Hibernate Tools 3.6.0

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * Postagem generated by hbm2java
 */
@Entity
@Table(name = "postagem", schema = "public"
)
public class Postagem implements java.io.Serializable {

    private int id;
    private String titulo;
    private String link;
    private Date data;
    private String conteudo;
    private Integer usuario;
    private Boolean status;
    private List<VideosPostagem> videosPostagems = new ArrayList<VideosPostagem>();
    private List<LinksQuestao> linksQuestaos = new ArrayList<LinksQuestao>();

    public Postagem() {
    }

    public Postagem(int id, Date data, String conteudo) {
        this.id = id;
        this.data = data;
        this.conteudo = conteudo;
    }

    public Postagem(int id, String titulo, String link, Date data, String conteudo, Integer usuario, Boolean status, List<VideosPostagem> videosPostagems, List<LinksQuestao> linksQuestaos) {
        this.id = id;
        this.titulo = titulo;
        this.link = link;
        this.data = data;
        this.conteudo = conteudo;
        this.usuario = usuario;
        this.status = status;
        this.videosPostagems = videosPostagems;
        this.linksQuestaos = linksQuestaos;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "titulo")
    public String getTitulo() {
        return this.titulo;
    }

    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    @Column(name = "link")
    public String getLink() {
        return this.link;
    }

    public void setLink(String link) {
        this.link = link;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "data")
    public Date getData() {
        return this.data;
    }

    public void setData(Date data) {
        this.data = data;
    }

    @Column(name = "conteudo", nullable = false)
    public String getConteudo() {
        return this.conteudo;
    }

    public void setConteudo(String conteudo) {
        this.conteudo = conteudo;
    }

    @Column(name = "usuario")
    public Integer getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Integer usuario) {
        this.usuario = usuario;
    }

    @Column(name = "status")
    public Boolean getStatus() {
        return this.status;
    }

    public void setStatus(Boolean status) {
        this.status = status;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "postagem", targetEntity = VideosPostagem.class, orphanRemoval = true)
    @Fetch(FetchMode.SUBSELECT)
    public List<VideosPostagem> getVideosPostagems() {
        return this.videosPostagems;
    }

    public void setVideosPostagems(List<VideosPostagem> videosPostagems) {
        this.videosPostagems = videosPostagems;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "postagem", targetEntity = LinksQuestao.class)
    @Fetch(FetchMode.SUBSELECT)
    public List<LinksQuestao> getLinksQuestaos() {
        return this.linksQuestaos;
    }

    public void setLinksQuestaos(List<LinksQuestao> linksQuestaos) {
        this.linksQuestaos = linksQuestaos;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 73 * hash + getId();
        hash = 73 * hash + (getTitulo() != null ? getTitulo().hashCode() : 0);
        hash = 73 * hash + (getLink() != null ? getLink().hashCode() : 0);
        hash = 73 * hash + (getData() != null ? getData().hashCode() : 0);
        hash = 73 * hash + (getConteudo() != null ? getConteudo().hashCode() : 0);
        hash = 73 * hash + (getUsuario() != null ? getUsuario().hashCode() : 0);
        hash = 73 * hash + (getStatus() != null ? getStatus().hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Postagem other = (Postagem) obj;
        if (getId() != other.getId()) {
            return false;
        }
        if ((getTitulo() == null) ? (other.getTitulo() != null) : !getTitulo().equals(other.getTitulo())) {
            return false;
        }
        if ((getLink() == null) ? (other.getLink() != null) : !getLink().equals(other.getLink())) {
            return false;
        }
        if (getData() != other.getData() && (getData() == null || !getData().equals(other.getData()))) {
            return false;
        }
        if ((getConteudo() == null) ? (other.getConteudo() != null) : !getConteudo().equals(other.getConteudo())) {
            return false;
        }
        if (getUsuario() != other.getUsuario() && (getUsuario() == null || !getUsuario().equals(other.getUsuario()))) {
            return false;
        }
        if (getStatus() != other.getStatus() && (getStatus() == null || !getStatus().equals(other.getStatus()))) {
            return false;
        }
        return true;
    }

}
