package br.edu.uag.aruagi.model;
// Generated 09/08/2014 12:29:58 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * QuestaoTraduzPalavra generated by hbm2java
 */
@Entity
@Table(name = "questao_traduz_palavra", schema = "public"
)
public class QuestaoTraduzPalavra implements java.io.Serializable {

    private int id;
    private PalavraLatim palavraLatim;
    private PalavraPortugues palavraPortugues;
    private NivelQuestao nivelQuestao;
    private String titulo;
    private String enunciado;
    private boolean status;
    private Integer usuario;

    public QuestaoTraduzPalavra() {
    }

    public QuestaoTraduzPalavra(int id, PalavraLatim palavraLatim, NivelQuestao nivelQuestao, boolean status) {
        this.id = id;
        this.palavraLatim = palavraLatim;
        this.nivelQuestao = nivelQuestao;
        this.status = status;
    }

    public QuestaoTraduzPalavra(int id, PalavraLatim palavraLatim, NivelQuestao nivelQuestao, String titulo, String enunciado, boolean status, Integer usuario) {
        this.id = id;
        this.palavraLatim = palavraLatim;
        this.nivelQuestao = nivelQuestao;
        this.titulo = titulo;
        this.enunciado = enunciado;
        this.status = status;
        this.usuario = usuario;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "palavra_latim", nullable = false)
    public PalavraLatim getPalavraLatim() {
        return this.palavraLatim;
    }

    public void setPalavraLatim(PalavraLatim palavraLatim) {
        this.palavraLatim = palavraLatim;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "nivel", nullable = false)
    public NivelQuestao getNivelQuestao() {
        return this.nivelQuestao;
    }

    public void setNivelQuestao(NivelQuestao nivelQuestao) {
        this.nivelQuestao = nivelQuestao;
    }

    @Column(name = "titulo")
    public String getTitulo() {
        return this.titulo;
    }

    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    @Column(name = "enunciado")
    public String getEnunciado() {
        return this.enunciado;
    }

    public void setEnunciado(String enunciado) {
        this.enunciado = enunciado;
    }

    @Column(name = "status", nullable = false)
    public boolean isStatus() {
        return this.status;
    }

    public void setStatus(boolean status) {
        this.status = status;
    }

    @Column(name = "usuario")
    public Integer getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Integer usuario) {
        this.usuario = usuario;
    }
    
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "traducao", nullable = false)
    public PalavraPortugues getPalavraPortugues() {
        return this.palavraPortugues;
    }

    public void setPalavraPortugues(PalavraPortugues palavraPortugues) {
        this.palavraPortugues = palavraPortugues;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 17 * hash + this.id;
        hash = 17 * hash + (this.palavraLatim != null ? this.palavraLatim.hashCode() : 0);
        hash = 17 * hash + (this.nivelQuestao != null ? this.nivelQuestao.hashCode() : 0);
        hash = 17 * hash + (this.titulo != null ? this.titulo.hashCode() : 0);
        hash = 17 * hash + (this.enunciado != null ? this.enunciado.hashCode() : 0);
        hash = 17 * hash + (this.status ? 1 : 0);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final QuestaoTraduzPalavra other = (QuestaoTraduzPalavra) obj;
        if (this.id != other.id) {
            return false;
        }
        if (this.palavraLatim != other.palavraLatim && (this.palavraLatim == null || !this.palavraLatim.equals(other.palavraLatim))) {
            return false;
        }
        if (this.nivelQuestao != other.nivelQuestao && (this.nivelQuestao == null || !this.nivelQuestao.equals(other.nivelQuestao))) {
            return false;
        }
        if ((this.titulo == null) ? (other.titulo != null) : !this.titulo.equals(other.titulo)) {
            return false;
        }
        if ((this.enunciado == null) ? (other.enunciado != null) : !this.enunciado.equals(other.enunciado)) {
            return false;
        }
        if (this.status != other.status) {
            return false;
        }
        return true;
    }

}
