package br.edu.uag.aruagi.model;
// Generated 09/08/2014 12:29:58 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * QuestaoTraduzFrase generated by hbm2java
 */
@Entity
@Table(name = "questao_traduz_frase", schema = "public"
)
public class QuestaoTraduzFrase implements java.io.Serializable {

    private int id;
    private FraseLatim fraseLatim;
    private NivelQuestao nivelQuestao;
    private boolean status;
    private String enunciado;
    private String titulo;
    private Integer usuario;

    public QuestaoTraduzFrase() {
    }

    public QuestaoTraduzFrase(int id, FraseLatim fraseLatim, NivelQuestao nivelQuestao, boolean status) {
        this.id = id;
        this.fraseLatim = fraseLatim;
        this.nivelQuestao = nivelQuestao;
        this.status = status;
    }

    public QuestaoTraduzFrase(int id, FraseLatim fraseLatim, NivelQuestao nivelQuestao, boolean status, String enunciado, String titulo, Integer usuario) {
        this.id = id;
        this.fraseLatim = fraseLatim;
        this.nivelQuestao = nivelQuestao;
        this.status = status;
        this.enunciado = enunciado;
        this.titulo = titulo;
        this.usuario = usuario;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "frase_latim", nullable = false)
    public FraseLatim getFraseLatim() {
        return this.fraseLatim;
    }

    public void setFraseLatim(FraseLatim fraseLatim) {
        this.fraseLatim = fraseLatim;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "nivel", nullable = false)
    public NivelQuestao getNivelQuestao() {
        return this.nivelQuestao;
    }

    public void setNivelQuestao(NivelQuestao nivelQuestao) {
        this.nivelQuestao = nivelQuestao;
    }

    @Column(name = "status", nullable = false)
    public boolean isStatus() {
        return this.status;
    }

    public void setStatus(boolean status) {
        this.status = status;
    }

    @Column(name = "enunciado")
    public String getEnunciado() {
        return this.enunciado;
    }

    public void setEnunciado(String enunciado) {
        this.enunciado = enunciado;
    }

    @Column(name = "titulo")
    public String getTitulo() {
        return this.titulo;
    }

    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    @Column(name = "usuario")
    public Integer getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Integer usuario) {
        this.usuario = usuario;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 83 * hash + this.id;
        hash = 83 * hash + (this.fraseLatim != null ? this.fraseLatim.hashCode() : 0);
        hash = 83 * hash + (this.nivelQuestao != null ? this.nivelQuestao.hashCode() : 0);
        hash = 83 * hash + (this.status ? 1 : 0);
        hash = 83 * hash + (this.enunciado != null ? this.enunciado.hashCode() : 0);
        hash = 83 * hash + (this.titulo != null ? this.titulo.hashCode() : 0);
        hash = 83 * hash + (this.usuario != null ? this.usuario.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final QuestaoTraduzFrase other = (QuestaoTraduzFrase) obj;
        if (this.id != other.id) {
            return false;
        }
        if (this.fraseLatim != other.fraseLatim && (this.fraseLatim == null || !this.fraseLatim.equals(other.fraseLatim))) {
            return false;
        }
        if (this.nivelQuestao != other.nivelQuestao && (this.nivelQuestao == null || !this.nivelQuestao.equals(other.nivelQuestao))) {
            return false;
        }
        if (this.status != other.status) {
            return false;
        }
        if ((this.enunciado == null) ? (other.enunciado != null) : !this.enunciado.equals(other.enunciado)) {
            return false;
        }
        if ((this.titulo == null) ? (other.titulo != null) : !this.titulo.equals(other.titulo)) {
            return false;
        }
        if (this.usuario != other.usuario && (this.usuario == null || !this.usuario.equals(other.usuario))) {
            return false;
        }
        return true;
    }

}
