package br.edu.uag.aruagi.model;
// Generated 09/08/2014 12:29:58 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * TipoQuestao generated by hbm2java
 */
@Entity
@Table(name = "tipo_questao", schema = "public"
)
public class TipoQuestao implements java.io.Serializable {

    private int id;
    private boolean status;
    private String descricao;
    private String nomeTabelaBanco;
    private Integer usuario;
    private Set atividadeQuestaos = new HashSet(0);

    public TipoQuestao() {
    }

    public TipoQuestao(int id, boolean status, String descricao) {
        this.id = id;
        this.status = status;
        this.descricao = descricao;
    }

    public TipoQuestao(int id, boolean status, String descricao, String nomeTabelaBanco, Integer usuario, Set atividadeQuestaos) {
        this.id = id;
        this.status = status;
        this.descricao = descricao;
        this.nomeTabelaBanco = nomeTabelaBanco;
        this.usuario = usuario;
        this.atividadeQuestaos = atividadeQuestaos;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "status", nullable = false)
    public boolean isStatus() {
        return this.status;
    }

    public void setStatus(boolean status) {
        this.status = status;
    }

    @Column(name = "descricao", nullable = false)
    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    @Column(name = "nome_tabela_banco")
    public String getNomeTabelaBanco() {
        return this.nomeTabelaBanco;
    }

    public void setNomeTabelaBanco(String nomeTabelaBanco) {
        this.nomeTabelaBanco = nomeTabelaBanco;
    }

    @Column(name = "usuario")
    public Integer getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Integer usuario) {
        this.usuario = usuario;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "tipoQuestao", targetEntity = AtividadeQuestao.class)
    @Fetch(FetchMode.SUBSELECT)
    public Set getAtividadeQuestaos() {
        return this.atividadeQuestaos;
    }

    public void setAtividadeQuestaos(Set atividadeQuestaos) {
        this.atividadeQuestaos = atividadeQuestaos;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 17 * hash + this.id;
        hash = 17 * hash + (this.status ? 1 : 0);
        hash = 17 * hash + (this.descricao != null ? this.descricao.hashCode() : 0);
        hash = 17 * hash + (this.nomeTabelaBanco != null ? this.nomeTabelaBanco.hashCode() : 0);
        hash = 17 * hash + (this.usuario != null ? this.usuario.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final TipoQuestao other = (TipoQuestao) obj;
        if (this.id != other.id) {
            return false;
        }
        if (this.status != other.status) {
            return false;
        }
        if ((this.descricao == null) ? (other.descricao != null) : !this.descricao.equals(other.descricao)) {
            return false;
        }
        if ((this.nomeTabelaBanco == null) ? (other.nomeTabelaBanco != null) : !this.nomeTabelaBanco.equals(other.nomeTabelaBanco)) {
            return false;
        }
        if (this.usuario != other.usuario && (this.usuario == null || !this.usuario.equals(other.usuario))) {
            return false;
        }
        return true;
    }

}
