package br.edu.uag.aruagi.model;
// Generated 09/08/2014 12:29:58 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TraduzFraseId generated by hbm2java
 */
@Embeddable
public class TraduzFraseId implements java.io.Serializable {

    private int fraseLatim;
    private int frasePortugues;

    public TraduzFraseId() {
    }

    public TraduzFraseId(int fraseLatim, int frasePortugues) {
        this.fraseLatim = fraseLatim;
        this.frasePortugues = frasePortugues;
    }

    @Column(name = "frase_latim", nullable = false)
    public int getFraseLatim() {
        return this.fraseLatim;
    }

    public void setFraseLatim(int fraseLatim) {
        this.fraseLatim = fraseLatim;
    }

    @Column(name = "frase_portugues", nullable = false)
    public int getFrasePortugues() {
        return this.frasePortugues;
    }

    public void setFrasePortugues(int frasePortugues) {
        this.frasePortugues = frasePortugues;
    }

    @Override
    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof TraduzFraseId)) {
            return false;
        }
        TraduzFraseId castOther = (TraduzFraseId) other;

        return (this.getFraseLatim() == castOther.getFraseLatim())
                && (this.getFrasePortugues() == castOther.getFrasePortugues());
    }

    @Override
    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getFraseLatim();
        result = 37 * result + this.getFrasePortugues();
        return result;
    }

}
