package br.edu.uag.aruagi.model;
// Generated 09/08/2014 12:29:58 by Hibernate Tools 3.6.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TraduzPalavra generated by hbm2java
 */
@Entity
@Table(name = "traduz_palavra", schema = "public"
)
public class TraduzPalavra implements java.io.Serializable {
    
    private TraduzPalavraId id;
    private PalavraPortugues palavraPortugues;
    private PalavraLatim palavraLatim;
    private Integer usuario;
    private Boolean status;
    
    public TraduzPalavra() {
    }
    
    public TraduzPalavra(TraduzPalavraId id, PalavraPortugues palavraPortugues, PalavraLatim palavraLatim) {
        this.id = id;
        this.palavraPortugues = palavraPortugues;
        this.palavraLatim = palavraLatim;
    }
    
    public TraduzPalavra(TraduzPalavraId id, PalavraPortugues palavraPortugues, PalavraLatim palavraLatim, Integer usuario) {
        this.id = id;
        this.palavraPortugues = palavraPortugues;
        this.palavraLatim = palavraLatim;
        this.usuario = usuario;
    }
    
    @EmbeddedId
    @AttributeOverrides({
        @AttributeOverride(name = "palavraLatim", column = @Column(name = "palavra_latim", nullable = false)),
        @AttributeOverride(name = "palavraPortugues", column = @Column(name = "palavra_portugues", nullable = false))})
    public TraduzPalavraId getId() {
        return this.id;
    }
    
    public void setId(TraduzPalavraId id) {
        this.id = id;
    }
    
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "palavra_portugues", nullable = false, insertable = false, updatable = false)
    public PalavraPortugues getPalavraPortugues() {
        return this.palavraPortugues;
    }
    
    public void setPalavraPortugues(PalavraPortugues palavraPortugues) {
        this.getId().setPalavraPortugues(palavraPortugues.getId());
        this.palavraPortugues = palavraPortugues;
    }
    
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "palavra_latim", nullable = false, insertable = false, updatable = false)
    public PalavraLatim getPalavraLatim() {
        return this.palavraLatim;
    }
    
    public void setPalavraLatim(PalavraLatim palavraLatim) {
        this.getId().setPalavraLatim(palavraLatim.getId());
        this.palavraLatim = palavraLatim;
    }
    
    @Column(name = "usuario")
    public Integer getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Integer usuario) {
        this.usuario = usuario;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }
    
    @Column(name = "status")
    public Boolean getStatus() {
        return this.status;
    }
    
    @Override
    public int hashCode() {
        int hash = 3;
        hash = 29 * hash + (this.id != null ? this.id.hashCode() : 0);
        hash = 29 * hash + (this.palavraPortugues != null ? this.palavraPortugues.hashCode() : 0);
        hash = 29 * hash + (this.palavraLatim != null ? this.palavraLatim.hashCode() : 0);
        hash = 29 * hash + (this.usuario != null ? this.usuario.hashCode() : 0);
        hash = 29 * hash + (this.status != null ? this.status.hashCode() : 0);
        return hash;
    }
    
    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final TraduzPalavra other = (TraduzPalavra) obj;
        if (this.id != other.id && (this.id == null || !this.id.equals(other.id))) {
            return false;
        }
        if (this.palavraPortugues != other.palavraPortugues && (this.palavraPortugues == null || !this.palavraPortugues.equals(other.palavraPortugues))) {
            return false;
        }
        if (this.palavraLatim != other.palavraLatim && (this.palavraLatim == null || !this.palavraLatim.equals(other.palavraLatim))) {
            return false;
        }
        if (this.usuario != other.usuario && (this.usuario == null || !this.usuario.equals(other.usuario))) {
            return false;
        }
        if (this.status != other.status && (this.status == null || !this.status.equals(other.status))) {
            return false;
        }
        return true;
    }
    
}
