package br.edu.uag.aruagi.model;
// Generated 09/08/2014 12:29:58 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TraduzPalavraId generated by hbm2java
 */
@Embeddable
public class TraduzPalavraId implements java.io.Serializable {

    private int palavraLatim;
    private int palavraPortugues;

    public TraduzPalavraId() {
    }

    public TraduzPalavraId(int palavraLatim, int palavraPortugues) {
        this.palavraLatim = palavraLatim;
        this.palavraPortugues = palavraPortugues;
    }

    @Column(name = "palavra_latim", nullable = false)
    public int getPalavraLatim() {
        return this.palavraLatim;
    }

    public void setPalavraLatim(int palavraLatim) {
        this.palavraLatim = palavraLatim;
    }

    @Column(name = "palavra_portugues", nullable = false)
    public int getPalavraPortugues() {
        return this.palavraPortugues;
    }

    public void setPalavraPortugues(int palavraPortugues) {
        this.palavraPortugues = palavraPortugues;
    }

    @Override
    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof TraduzPalavraId)) {
            return false;
        }
        TraduzPalavraId castOther = (TraduzPalavraId) other;

        return (this.getPalavraLatim() == castOther.getPalavraLatim())
                && (this.getPalavraPortugues() == castOther.getPalavraPortugues());
    }

    @Override
    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getPalavraLatim();
        result = 37 * result + this.getPalavraPortugues();
        return result;
    }

}
