package br.edu.uag.aruagi.model;
// Generated 09/08/2014 12:29:58 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VideosPostagem generated by hbm2java
 */
@Entity
@Table(name = "videos_postagem", schema = "public"
)
public class VideosPostagem implements java.io.Serializable {

    private int id;
    private Videos videos;
    private Postagem postagem;
    private Integer usuario;

    public VideosPostagem() {
    }

    public VideosPostagem(int id, Videos videos, Postagem postagem) {
        this.id = id;
        this.videos = videos;
        this.postagem = postagem;
    }

    public VideosPostagem(int id, Videos videos, Postagem postagem, Integer usuario) {
        this.id = id;
        this.videos = videos;
        this.postagem = postagem;
        this.usuario = usuario;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "videos", nullable = false)
    public Videos getVideos() {
        return this.videos;
    }

    public void setVideos(Videos videos) {
        this.videos = videos;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "postagem", nullable = false)
    public Postagem getPostagem() {
        return this.postagem;
    }

    public void setPostagem(Postagem postagem) {
        this.postagem = postagem;
    }

    @Column(name = "usuario")
    public Integer getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Integer usuario) {
        this.usuario = usuario;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 71 * hash + getId();
        hash = 71 * hash + (getVideos() != null ? getVideos().hashCode() : 0);
        hash = 71 * hash + (getPostagem() != null ? getPostagem().hashCode() : 0);
        hash = 71 * hash + (getUsuario() != null ? getUsuario().hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final VideosPostagem other = (VideosPostagem) obj;
        if (getId() != other.getId()) {
            return false;
        }
        if (getVideos() != other.getVideos() && (getVideos() == null || !getVideos().equals(other.getVideos()))) {
            return false;
        }
        if (getPostagem() != other.getPostagem() && (getPostagem() == null || !getPostagem().equals(other.getPostagem()))) {
            return false;
        }
        if (getUsuario() != other.getUsuario() && (getUsuario() == null || !getUsuario().equals(other.getUsuario()))) {
            return false;
        }
        return true;
    }

}
