package br.edu.uag.aruagi.model;
// Generated 09/08/2014 12:29:58 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VideosPostagem generated by hbm2java
 */
@Entity
@Table(name = "videos_postagem", schema = "public"
)
public class VideosPostagem implements java.io.Serializable {

    private int id;
    private Videos videos;
    private Postagem postagem;
    private Integer usuario;

    public VideosPostagem() {
    }

    public VideosPostagem(int id, Videos videos, Postagem postagem) {
        this.id = id;
        this.videos = videos;
        this.postagem = postagem;
    }

    public VideosPostagem(int id, Videos videos, Postagem postagem, Integer usuario) {
        this.id = id;
        this.videos = videos;
        this.postagem = postagem;
        this.usuario = usuario;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "videos", nullable = false)
    public Videos getVideos() {
        return this.videos;
    }

    public void setVideos(Videos videos) {
        this.videos = videos;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "postagem", nullable = false)
    public Postagem getPostagem() {
        return this.postagem;
    }

    public void setPostagem(Postagem postagem) {
        this.postagem = postagem;
    }

    @Column(name = "usuario")
    public Integer getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Integer usuario) {
        this.usuario = usuario;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 71 * hash + this.id;
        hash = 71 * hash + (this.videos != null ? this.videos.hashCode() : 0);
        hash = 71 * hash + (this.postagem != null ? this.postagem.hashCode() : 0);
        hash = 71 * hash + (this.usuario != null ? this.usuario.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final VideosPostagem other = (VideosPostagem) obj;
        if (this.id != other.id) {
            return false;
        }
        if (this.videos != other.videos && (this.videos == null || !this.videos.equals(other.videos))) {
            return false;
        }
        if (this.postagem != other.postagem && (this.postagem == null || !this.postagem.equals(other.postagem))) {
            return false;
        }
        if (this.usuario != other.usuario && (this.usuario == null || !this.usuario.equals(other.usuario))) {
            return false;
        }
        return true;
    }

}
